// DEPLOYED RENDER
### Get all events
GET https://cse341-finalproject-87ca.onrender.com/events

### Get event by id
GET https://cse341-finalproject-87ca.onrender.com/events/66a021d22775db19e960349c


### Create event
POST https://cse341-finalproject-87ca.onrender.com/events HTTP/1.1
content-type: application/json

{
    "title": "TEST General Conference October 2024",
    "description": "General conference is the worldwide gathering of The Church of Jesus Christ of Latter-day Saints. The Church invites everyone — of all faiths, beliefs and backgrounds from everywhere in the world — to watch, listen and participate.",
    "date": "2024-10-05",
    "location": "Temple Square, Salt Lake City, Utah, USA",
    "created_by": "The Admin"
}

### Update event
PUT https://cse341-finalproject-87ca.onrender.com/events/66a021d22775db19e960349c HTTP/1.1
content-type: application/json

{
    "title": "TEST General Conference April 2025",
    "description": "General conference is the worldwide gathering of The Church of Jesus Christ of Latter-day Saints. The Church invites everyone — of all faiths, beliefs and backgrounds from everywhere in the world — to watch, listen and participate.",
    "date": "2025-04-05",
    "location": "Temple Square, Salt Lake City, Utah, USA",
    "created_by": "The Admin"
}

### Delete event
DELETE  https://cse341-finalproject-87ca.onrender.com/events/66a021d22775db19e960349c HTTP/1.1